### ISSUE TITLE
yarn build begs to run pointless command

### ISSUE THREAD

**Issue by matkoniecz** [stevage/which-geocoder#42]
yarn build asks to run

`yarn upgrade caniuse-lite browserslist`

that appears to have no effects

Is it possible to suppres this?

**Comment by stevage** [comment]
I see that across all my projects that use this stack. I've never bother investigating it.

**Comment by matkoniecz** [comment]
And I am not planning to use `yarn` elsewhere so I guess that it is not a good idea to keep it open forever.
